### ISSUE TITLE
Add pathsegments functionality to `this_dir`

### ISSUE THREAD

**Issue by heetbeet** [AutoActuary/locate#7]
The idea is to get a path relative to the current directly without wrapping further `Path` or os.path functionality over the returned path.

```
>>> this_dir("path", "segment")
WindowsPath("c:/dir_of_this_scripts/path/segment")
```

https://github.com/AutoActuary/locate/tree/feature-to-add-pathsegments-directly-to-this_dir

**Comment by heetbeet** [comment]
@rudolfbyker is this a good idea? Seems fine to me, it basically mimicks `Paths` idea of file construction etc. But maybe it should be a different and new function?

**Comment by rudolfbyker** [comment]
This is just syntactic sugar for `this_dir().joinpath("path", "segment")`. I see no use for it.
